const { Room } = require('../models');
const roomData = [
  {
    room_num: 101,
    room_type: "Single Room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "Queen",
    room_size: "16*20",
    price: 80,
    branch_id: 1,
  },
  {
    room_num: 102,
    room_type: "Double room",
    Max_occupancy: 2,
    num_beds: 2,
    bed_size: "Twin",
    room_size: "20*24",
    price: 100,
    branch_id: 1,
  },
  {
    room_num: 103,
    room_type: "Studio",
    Max_occupancy: 4,
    num_beds: 2,
    bed_size: "Queen",
    room_size: "30*36",
    price: 200,
    branch_id: 1,
  },
  {
    room_num: 104,
    room_type: "Deluxe room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "King",
    room_size: "24*30",
    price: 150,
    branch_id: 1,
  },
  {
    room_num: 101,
    room_type: "Single Room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "Queen",
    room_size: "16*20",
    price: 100,
    branch_id: 2,
  },
  {
    room_num: 102,
    room_type: "Double room",
    Max_occupancy: 2,
    num_beds: 2,
    bed_size: "Twin",
    room_size: "20*24",
    price: 110,
    branch_id: 2,
  },
  {
    room_num: 103,
    room_type: "Studio",
    Max_occupancy: 4,
    num_beds: 2,
    bed_size: "Queen",
    room_size: "30*36",
    price: 220,
    branch_id: 2,
  },
  {
    room_num: 104,
    room_type: "Deluxe room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "King",
    room_size: "24*30",
    price: 160,
    branch_id: 2,
  },
  {
    room_num: 101,
    room_type: "Single Room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "Queen",
    room_size: "16*20",
    price: 70,
    branch_id: 3,
  },
  {
    room_num: 102,
    room_type: "Double room",
    Max_occupancy: 2,
    num_beds: 2,
    bed_size: "Twin",
    room_size: "20*24",
    price: 90,
    branch_id: 3,
  },
  {
    room_num: 103,
    room_type: "Studio",
    Max_occupancy: 4,
    num_beds: 2,
    bed_size: "Queen",
    room_size: "30*36",
    price: 180,
    branch_id: 3,
  },
  {
    room_num: 104,
    room_type: "Deluxe room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "King",
    room_size: "24*30",
    price: 140,
    branch_id: 3,
  },
  {
    room_num: 101,
    room_type: "Single Room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "Queen",
    room_size: "16*20",
    price: 120,
    branch_id: 4,
  },
  {
    room_num: 102,
    room_type: "Double room",
    Max_occupancy: 2,
    num_beds: 2,
    bed_size: "Twin",
    room_size: "20*24",
    price: 140,
    branch_id: 4,
  },
  {
    room_num: 103,
    room_type: "Studio",
    Max_occupancy: 4,
    num_beds: 2,
    bed_size: "Queen",
    room_size: "30*36",
    price: 240,
    branch_id: 4,
  },
  {
    room_num: 104,
    room_type: "Deluxe room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "King",
    room_size: "24*30",
    price: 180,
    branch_id: 4,
  },
  {
    room_num: 101,
    room_type: "Single Room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "Queen",
    room_size: "16*20",
    price: 95,
    branch_id: 5,
  },
  {
    room_num: 102,
    room_type: "Double room",
    Max_occupancy: 2,
    num_beds: 2,
    bed_size: "Twin",
    room_size: "20*24",
    price: 110,
    branch_id: 5,
  },
  {
    room_num: 103,
    room_type: "Studio",
    Max_occupancy: 4,
    num_beds: 2,
    bed_size: "Queen",
    room_size: "30*36",
    price: 300,
    branch_id: 5,
  },
  {
    room_num: 104,
    room_type: "Deluxe room",
    Max_occupancy: 2,
    num_beds: 1,
    bed_size: "King",
    room_size: "24*30",
    price: 200,
    branch_id: 5,
  },
];

const seedRooms = () => Room.bulkCreate(roomData);

module.exports = seedRooms;
